# Generated by Django 5.1.5 on 2025-01-20 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, 
                    primary_key=True, 
                    serialize=False, 
                    verbose_name='ID'
                )),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, 
                    primary_key=True, 
                    serialize=False, 
                    verbose_name='ID'
                )),
                ('dealer_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(
                    choices=[
                        ('SEDAN', 'Sedan'),
                        ('SUV', 'SUV'),
                        ('WAGON', 'Wagon')
                    ],
                    default='SEDAN',
                    max_length=20
                )),
                ('year', models.DateField()),
                ('car_make', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, 
                    to='djangoapp.carmake'
                )),
            ],
        ),
    ]
