# Generated by Django 5.1.5 on 2025-01-20 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='dealer_id',
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True
            ),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='year',
            field=models.IntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(2023),
                    django.core.validators.MinValueValidator(2015)
                ]
            ),
        ),
    ]
